version: '2'
services:
  submin:
    image: croesus/submin:latest
    container_name: submin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - SUBMIN_EXTERNAL_PORT=8080
      - SUBMIN_HOSTNAME=127.0.0.1
      - SUBMIN_ADMIN_MAIL=admin@svn.local
      - SUBMIN_DATA_DIR=/var/lib/submin
      - SUBMIN_SMTP_HOSTNAME=localhost
      - SUBMIN_SMTP_PORT=25
    volumes:
      - ./svn/repos:/var/lib/svn
      - ./svn/log:/var/log/apache2

